name: Tokyo Spring 2016
favicon: null
layout_spectrum: 0.5211539443116635
typography_spectrum: 0.4956186308991164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9099800793919712
  lightness: 0.9521372956223786
  saturation: 0.2115587005391717
  rhythmicContrast: 0.4697121740318835
purpose: []
